# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='NoImage.png', upload_to='photos/%Y/%m/%d'),
        ),
    ]
