# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 02:30
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
